services:
  seny-auth:
    container_name: seny-auth
    build:
      context: .
      target: build
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 3002:3002
    command: npm run dev
    networks:
      - seny-network-auth

networks:
  seny-network-auth:
    driver: bridge
    name: seny-network
    external: true